<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Lot 1 : socle de la base clientele (clients, chantiers, fournisseurs),
 * en-tetes de documents pour la reprise d'historique, sessions d'import,
 * compteurs de numerotation et comptes utilisateurs.
 */
final class Version20260921202754 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Lot 1 - Base clientele, chantiers, fournisseurs, documents, imports et sequences de numerotation';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE "user" (id UUID NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, nom_complet VARCHAR(120) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_user_email ON "user" (email)');
        $this->addSql('CREATE TABLE chantier (id UUID NOT NULL, libelle VARCHAR(180) NOT NULL, notes TEXT DEFAULT NULL, actif BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, adresse_ligne1 VARCHAR(255) DEFAULT NULL, adresse_ligne2 VARCHAR(255) DEFAULT NULL, adresse_code_postal VARCHAR(10) DEFAULT NULL, adresse_ville VARCHAR(120) DEFAULT NULL, adresse_pays VARCHAR(80) DEFAULT \'France\', client_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_636F27F619EB6921 ON chantier (client_id)');
        $this->addSql('CREATE TABLE client (id UUID NOT NULL, numero_client VARCHAR(20) NOT NULL, typologie VARCHAR(20) NOT NULL, civilite VARCHAR(10) DEFAULT NULL, nom VARCHAR(120) DEFAULT NULL, prenom VARCHAR(120) DEFAULT NULL, raison_sociale VARCHAR(180) DEFAULT NULL, telephone VARCHAR(30) DEFAULT NULL, email VARCHAR(180) DEFAULT NULL, siret VARCHAR(14) DEFAULT NULL, numero_tva_intracom VARCHAR(20) DEFAULT NULL, notes TEXT DEFAULT NULL, actif BOOLEAN DEFAULT true NOT NULL, importe BOOLEAN DEFAULT false NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, facturation_ligne1 VARCHAR(255) DEFAULT NULL, facturation_ligne2 VARCHAR(255) DEFAULT NULL, facturation_code_postal VARCHAR(10) DEFAULT NULL, facturation_ville VARCHAR(120) DEFAULT NULL, facturation_pays VARCHAR(80) DEFAULT \'France\', PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C74404559F83176F ON client (numero_client)');
        $this->addSql('CREATE TABLE document (id UUID NOT NULL, numero VARCHAR(30) NOT NULL, type VARCHAR(30) NOT NULL, statut VARCHAR(20) NOT NULL, date_emission DATE NOT NULL, date_echeance DATE DEFAULT NULL, objet VARCHAR(255) DEFAULT NULL, montant_ht NUMERIC(12, 2) DEFAULT \'0.00\' NOT NULL, montant_tva NUMERIC(12, 2) DEFAULT \'0.00\' NOT NULL, montant_ttc NUMERIC(12, 2) DEFAULT \'0.00\' NOT NULL, legacy BOOLEAN DEFAULT false NOT NULL, verrouille BOOLEAN DEFAULT false NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, client_id UUID NOT NULL, chantier_id UUID DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_document_client_date ON document (client_id, date_emission)');
        $this->addSql('CREATE UNIQUE INDEX uniq_document_numero ON document (numero)');
        $this->addSql('CREATE INDEX IDX_D8698A7619EB6921 ON document (client_id)');
        $this->addSql('CREATE INDEX IDX_D8698A76D0C0049D ON document (chantier_id)');
        $this->addSql('CREATE TABLE fournisseur (id UUID NOT NULL, nom VARCHAR(180) NOT NULL, contact_nom VARCHAR(120) DEFAULT NULL, telephone VARCHAR(30) DEFAULT NULL, email VARCHAR(180) DEFAULT NULL, site_web VARCHAR(255) DEFAULT NULL, siret VARCHAR(14) DEFAULT NULL, notes TEXT DEFAULT NULL, actif BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, adresse_ligne1 VARCHAR(255) DEFAULT NULL, adresse_ligne2 VARCHAR(255) DEFAULT NULL, adresse_code_postal VARCHAR(10) DEFAULT NULL, adresse_ville VARCHAR(120) DEFAULT NULL, adresse_pays VARCHAR(80) DEFAULT \'France\', PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_fournisseur_nom ON fournisseur (nom)');
        $this->addSql('CREATE TABLE import (id UUID NOT NULL, type VARCHAR(20) NOT NULL, statut VARCHAR(30) NOT NULL, nom_fichier VARCHAR(255) NOT NULL, chemin_fichier VARCHAR(255) NOT NULL, extension VARCHAR(10) NOT NULL, colonnes_detectees JSON NOT NULL, apercu JSON NOT NULL, mapping JSON NOT NULL, nb_lignes INT NOT NULL, nb_succes INT NOT NULL, nb_erreurs INT NOT NULL, rapport JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, executed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE number_sequence (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, perimetre VARCHAR(40) NOT NULL, periode VARCHAR(20) NOT NULL, dernier_numero INT DEFAULT 0 NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_sequence_perimetre_periode ON number_sequence (perimetre, periode)');
        $this->addSql('ALTER TABLE chantier ADD CONSTRAINT FK_636F27F619EB6921 FOREIGN KEY (client_id) REFERENCES client (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE document ADD CONSTRAINT FK_D8698A7619EB6921 FOREIGN KEY (client_id) REFERENCES client (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE document ADD CONSTRAINT FK_D8698A76D0C0049D FOREIGN KEY (chantier_id) REFERENCES chantier (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE chantier DROP CONSTRAINT FK_636F27F619EB6921');
        $this->addSql('ALTER TABLE document DROP CONSTRAINT FK_D8698A7619EB6921');
        $this->addSql('ALTER TABLE document DROP CONSTRAINT FK_D8698A76D0C0049D');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE chantier');
        $this->addSql('DROP TABLE client');
        $this->addSql('DROP TABLE document');
        $this->addSql('DROP TABLE fournisseur');
        $this->addSql('DROP TABLE import');
        $this->addSql('DROP TABLE number_sequence');
    }
}
